# Generated by Django 6.0.5 on 2026-05-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('number', models.IntegerField(verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='имя')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группа',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='имя')),
                ('first_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студент',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='предмет')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предмет',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='имя')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('money', models.IntegerField(verbose_name='заработок')),
                ('age', models.IntegerField(verbose_name='возраст')),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учитель',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'домашнее задание',
                'verbose_name_plural': 'домашнее задание',
            },
        ),
    ]
