# Generated by Django 6.0.5 on 2026-05-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
                ('age', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'my_model2',
            },
        ),
    ]
