# Generated by Django 6.0.5 on 2026-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='car',
            field=models.ImageField(default=1, upload_to='clients/', verbose_name='фото машины'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='photo',
            field=models.ImageField(upload_to='subjects/', verbose_name='фото'),
        ),
    ]
