# Generated by Django 6.0.5 on 2026-05-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_mymodel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel2',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
