# Generated by Django 6.0.5 on 2026-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_mymodel2_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelTable(
            name='mymodel2',
            table='Student',
        ),
    ]
