# Generated by Django 6.0.5 on 2026-05-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_student_delete_mymodel_alter_mymodel2_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel2',
            new_name='Teacher',
        ),
    ]
