# Generated by Django 6.0.5 on 2026-05-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='имя',
        ),
    ]
