# Generated by Django 6.0.5 on 2026-05-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_school_rename_имя_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='password',
            field=models.CharField(max_length=100, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='director',
            name='username',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=100, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.CharField(max_length=100, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=100, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.CharField(max_length=100, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='money',
            field=models.CharField(max_length=100, verbose_name='заработок'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.group', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.teacher', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'домашнее задание',
                'verbose_name_plural': 'домашнее задание',
            },
        ),
    ]
