# Generated by Django 6.0.5 on 2026-05-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_director_password_alter_director_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('namee', models.CharField(max_length=100, verbose_name='имя')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='Subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.subject', verbose_name='Предмет'),
            preserve_default=False,
        ),
    ]
