# Generated by Django 6.0.5 on 2026-05-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_subject_homework_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='namee',
            new_name='name',
        ),
    ]
