# Generated by Django 6.0.5 on 2026-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_rename_namee_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
        migrations.AddField(
            model_name='subject',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='предмет'),
        ),
    ]
