# Generated by Django 6.0.5 on 2026-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_subject_title_subject_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='Subject',
            new_name='subject',
        ),
    ]
