# Generated by Django 6.0.5 on 2026-05-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_delete_director_delete_school_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
