# Generated by Django 6.0.5 on 2026-05-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_alter_group_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
