# Generated by Django 6.0.5 on 2026-05-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_group_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='username',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='password',
        ),
    ]
