# Generated by Django 6.0.5 on 2026-05-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_rename_username_group_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'домашнее задание', 'verbose_name_plural': 'домашнее задание'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='title',
            new_name='username',
        ),
        migrations.AddField(
            model_name='subject',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='пароль'),
            preserve_default=False,
        ),
    ]
