# Generated by Django 6.0.5 on 2026-05-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_subject_options_rename_title_group_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предмет'},
        ),
    ]
