# Generated by Django 6.0.5 on 2026-05-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_alter_subject_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='password',
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
