# Generated by Django 6.0.5 on 2026-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_remove_subject_name_remove_subject_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='предмет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='пароль'),
            preserve_default=False,
        ),
    ]
