# Generated by Django 6.0.5 on 2026-05-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_remove_subject_title_subject_name_subject_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='password',
        ),
    ]
