# Generated by Django 6.0.5 on 2026-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_remove_subject_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='money',
            field=models.IntegerField(verbose_name='заработок'),
        ),
    ]
